/*
 * This source file was generated by the Gradle 'init' task
 */
package be.kuleuven;

import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) {
        try {
            App.createDb();
            App.verifyDbContents();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void createDb() throws SQLException {
        var connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/school?allowMultiQueries=true",
                "root", "");
        var s = connection.createStatement();
        s.executeUpdate("""
                DROP TABLE IF EXISTS student;

                CREATE TABLE student(
                    studnr INT NOT NULL PRIMARY KEY,
                    naam VARCHAR(200) NOT NULL,
                    voornaam VARCHAR(200),
                    goedbezig BOOLEAN
                );

                INSERT INTO student (studnr, naam, voornaam, goedbezig) VALUES
                    (123, 'Trekhaak', 'Jaak', 0),
                    (456, 'Peeters', 'Jos', 0),
                    (890, 'Dongmans', 'Ding', 1);
                """);
        s.close();
        connection.close();
    }

    public static void verifyDbContents() throws SQLException {
        var connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/school?allowMultiQueries=true",
                "root", "");
        var s = connection.createStatement();
        var result = s.executeQuery("SELECT COUNT(*) as cnt FROM student;");
        while (result.next()) {
            System.out.println("Assert that number of rows is 3: " + (result.getInt("cnt") == 3));
            assert result.getInt("cnt") == 1;
        }
        s.close();
        connection.close();
    }
}

